### ISSUE TITLE
Does not work on Android 12

### ISSUE THREAD

**Issue by danielniccoli** [pembem22/connect-plus#53]
App loads.

Screen shows "searching" and there is a spinning wheel.

Then app does not respond any longer and needs to be terminated.

**Comment by pembem22** [comment]
Hi, I need more details to get an idea of what might be going on. There were some changes in Bluetooth permissions on Android 12, but it should affect ConnectPlus right now because it's not targeting version 12 yet.

1. By "app does not respond any longer and needs to be terminated" do you mean the [App Not Responding dialog](https://developer.android.com/topic/performance/vitals/anr)?
2. Does this happen always or only when there's a speaker nearby?
3. Have you given all required permissions to the app and was Bluetooth enabled?

Also, if you can record logs using ADB and upload them, that would be very helpful.

**Comment by pembem22** [comment]
I've uploaded a new build, can you check if the problem persists?

**Comment by danielniccoli** [comment]
The app does not load and I am able to start the firmware flashing.
